export const basicData = [
    { label: "Brand", name: "brand", placeHolder: "Eg. Hyundai" },
    { label: "Name", name: "name", placeHolder: "Eg. Creta" },
    { label: "Variant", name: "variant", placeHolder: "Eg. SX(O) Turbo" },
    { label: "KM Driven", name: "km_driven", isNumber: true, placeHolder: "Eg. 45,000" },
    { label: "Fuel Type", name: "fuel_type", placeHolder: "Eg. Petrol" },
    { label: "Body Type", name: "body_type", placeHolder: "Eg. SUV" },
    { label: "Transmission Type", name: "transmission_type", placeHolder: "Eg. Automatic" },
    { label: "Price", name: "price", isNumber: true, placeHolder: "Eg. 12,50,000" },
    { label: "Location", name: "location", placeHolder: "Eg. Bangalore" },
    { label: "Insurance", name: "insurance", placeHolder: "Eg. Valid till Dec 2025" },
    { label: "No of Seats", name: "no_of_seats", isNumber: true, placeHolder: "Eg. 5" },
    { label: "Reg Number", name: "reg_number", placeHolder: "Eg. KA03AB1234" },
    { label: "Ownership", name: "ownership", isNumber: true, placeHolder: "Eg. 2" },
    { label: "Engine Displacement", name: "engine_displacement", isNumber: true, placeHolder: "Eg. 1497 cc" },
    { label: "Highway Mileage", name: "highway_mileage", isNumber: true, placeHolder: "Eg. 18 kmpl" },
    { label: "Make Year", name: "make_year", isNumber: true, placeHolder: "Eg. 2020" },
    { label: "Reg Year", name: "reg_year", isNumber: true, placeHolder: "Eg. 2021" },

];

export const featuresData = {
    "comfort-and-convenience": [
        { label: "Power steering", value: "power-steering" },
        { label: "Air conditioner", value: "air-conditioner" },
        { label: "Heater", value: "heater" },
        { label: "Adjustable steering", value: "adjustable-steering" },
        { label: "Automatic climate control", value: "automatic-climate-control" },
        { label: "Air quality control", value: "air-quality-control" },
        { label: "Remote Trunk opener", value: "remote-trunk-opener" },
        { label: "Remote fuel lid opener", value: "remote-fuel-lid-opener" },
        { label: "Low fuel warning light", value: "low-fuel-warning-light" },
        { label: "Accessory power outlet", value: "accessory-power-outlet" },
        { label: "Trunk light", value: "trunk-light" },
        { label: "Rear seat headrest", value: "rear-seat-headrest" },
        { label: "Rear seat center arm rest", value: "rear-seat-center-arm-rest" },
        { label: "Rear AC vents", value: "rear-ac-vents" },
        { label: "Lumbar support", value: "lumbar-support" },
        { label: "Cruise control", value: "cruise-control" },
        { label: "Keyless entry", value: "keyless-entry" },
        { label: "Follow me home head lamps", value: "follow-me-home-head-lamps" },
        {
            label: "Height adjustable driver seat",
            value: "height-adjustable-driver-seat",
        },
        { label: "Ventilates seats", value: "ventilated-seats" },
        { label: "Vanity mirror", value: "vanity-mirror" },
        { label: "Rear reading lamp", value: "rear-reading-lamp" },
        { label: "Adjustable headrest", value: "adjustable-headrest" },
        {
            label: "Height adjustable front seat belt",
            value: "height-adjustable-front-seat-belt",
        },
        { label: "Engine Start/Stop button", value: "engine-start-stop-button" },
        { label: "Cooled glowbox", value: "cooled-glowbox" },
        { label: "Voice commands", value: "voice-commands" },
        { label: "Tailgate Ajar Warning", value: "tailgate-ajar-warning" },
        { label: "Battery saver", value: "battery-saver" },
        { label: "Automatic headlamps", value: "automatic-headlamps" },
        { label: "Paddle shifters", value: "paddle-shifters" },
        { label: "Luggage hook and net", value: "luggage-hook-and-net" },
        { label: "Glowbox light", value: "glowbox-light" },
        { label: "Voice assisted sunroof", value: "voice-assisted-sunroof" },
        { label: "Gear shift indicator", value: "gear-shift-indicator" },
        { label: "Idle start/stop button", value: "idle-start-stop-button" },
        { label: "Rear window sun blind", value: "rear-window-sun-blind" },
        { label: "Navigation system", value: "navigation-system" },
        { label: "Smart access card entry", value: "smart-access-card-entry" },
        { label: "Rear curtain", value: "rear-curtain" },
    ],

    interior: [
        { label: "Fabric upholstery", value: "fabric-upholstery" },
        { label: "Glow box", value: "glow-box" },
        {
            label: "Electronic multi-tripmeter",
            value: "electronic-multi-tripmeter",
        },
        { label: "Digital clock", value: "digital-clock" },
        { label: "Tachometer", value: "tachometer" },
        {
            label: "Outside temperature display",
            value: "outside-temperature-display",
        },
        { label: "Digital odometer", value: "digital-odometer" },
        {
            label: "Driving experience control eco",
            value: "driving-experience-control-eco",
        },
        { label: "Leather seats", value: "leather-seats" },
        {
            label: "Leather wrapped steering wheel",
            value: "leather-wrapped-steering-wheel",
        },
        { label: "Cigarette lighter", value: "cigarette-lighter" },
        { label: "Digital cluster", value: "digital-cluster" },
        { label: "Dual tone dashboard", value: "dual-tone-dashboard" },
        {
            label: "Leather wrap gear-shift selector",
            value: "leather-wrap-gear-shift-selector",
        },
    ],

    exterior: [
        { label: "Adjustable headlamps", value: "adjustable-headlamps" },
        { label: "Rear window defogger", value: "rear-window-defogger" },
        { label: "Wheel covers", value: "wheel-covers" },
        { label: "ORVM turn indicators", value: "orvm-turn-indicators" },
        { label: "Integrated antenna", value: "integrated-antenna" },
        { label: "Halogen headlamps", value: "halogen-headlamps" },
        { label: "Roof rails", value: "roof-rails" },
        { label: "Power antenna", value: "power-antenna" },
        { label: "Tinted glass", value: "tinted-glass" },
        { label: "Rear spoiler", value: "rear-spoiler" },
        { label: "Chrome grille", value: "chrome-grille" },
        { label: "Chrome garnish", value: "chrome-garnish" },
        { label: "Fog lights front", value: "fog-lights-front" },
        { label: "Fog lights rear", value: "fog-lights-rear" },
        { label: "Rear window wiper", value: "rear-window-wiper" },
        { label: "Rear window washer", value: "rear-window-washer" },
        { label: "Alloy wheels", value: "alloy-wheels" },
        { label: "Smoke headlamps", value: "smoke-headlamps" },
        { label: "Cornering headlamps", value: "cornering-headlamps" },
        { label: "LED DRLs", value: "led-drls" },
        { label: "LED headlamps", value: "led-headlamps" },
        { label: "LED taillights", value: "led-taillights" },
        { label: "LED foglamps", value: "led-foglamps" },
        { label: "Rain sensing wiper", value: "rain-sensing-wiper" },
        { label: "Projector headlamps", value: "projector-headlamps" },
        { label: "Sunroof", value: "sunroof" },
    ],

    safety: [
        { label: "Brake assist", value: "brake-assist" },
        { label: "ABS", value: "abs" },
        { label: "Driver airbag", value: "driver-airbag" },
        { label: "Passenger airbag", value: "passenger-airbag" },
        { label: "Side airbag", value: "side-airbag" },
        { label: "Side airbag rear", value: "side-airbag-rear" },
        {
            label: "Day and night rear view mirror",
            value: "day-night-rear-view-mirror",
        },
        {
            label: "Passenger side rear view mirror",
            value: "passenger-side-rear-view-mirror",
        },
        { label: "Curtain airbag", value: "curtain-airbag" },
        { label: "EBD", value: "ebd" },
        { label: "Seat belt warning", value: "seat-belt-warning" },
        { label: "TPMS", value: "tpms" },
        { label: "Engine immobilizer", value: "engine-immobilizer" },
        { label: "ESC", value: "esc" },
        { label: "Speed alert", value: "speed-alert" },
        {
            label: "Speed sensing auto door lock",
            value: "speed-sensing-auto-door-lock",
        },
        { label: "ISOFIX mounts", value: "isofix-child-seat-mounts" },
        { label: "Hill assist", value: "hill-assist" },
        { label: "Hill descent control", value: "hill-descent-control" },
        {
            label: "Impact sensing auto door lock",
            value: "impact-sensing-auto-door-lock",
        },
        { label: "Central locking", value: "central-locking" },
        { label: "Power door locks", value: "power-door-locks" },
        { label: "Child safety locks", value: "child-safety-locks" },
        { label: "Rear seat belts", value: "rear-seat-belts" },
        { label: "Side impact beams", value: "side-impact-beams" },
        { label: "Front impact beams", value: "front-impact-beams" },
        { label: "Adjustable seats", value: "adjustable-seats" },
        {
            label: "Centrally mounted fuel tank",
            value: "centrally-mounted-fuel-tank",
        },
        { label: "Anti theft alarm", value: "anti-theft-alarm" },
        { label: "Door ajar warning", value: "door-ajar-warning" },
        {
            label: "Vehicle stability control",
            value: "vehicle-stability-control-system",
        },
        { label: "Crash sensor", value: "crash-sensor" },
        { label: "Engine check warning", value: "engine-check-warning" },
        { label: "Anti theft device", value: "anti-theft-device" },
        {
            label: "Pretensioners and force limiter seatbelts",
            value: "pretensioners-force-limiter-seatbelts",
        },
        { label: "Rear camera", value: "rear-camera" },
        { label: "Traction control", value: "traction-control" },
        { label: "360 view camera", value: "360-view-camera" },
    ],

    "infotainment-and-communication": [
        { label: "Radio", value: "radio" },
        { label: "USB & Auxiliary input", value: "usb-auxiliary-input" },
        { label: "Bluetooth connectivity", value: "bluetooth-connectivity" },
        { label: "Touchscreen", value: "touchscreen" },
        { label: "Android auto", value: "android-auto" },
        { label: "Apple carplay", value: "apple-carplay" },
        { label: "USB ports", value: "usb-ports" },
        {
            label: "Audio system remote control",
            value: "audio-system-remote-control",
        },
        { label: "Integrated 2DIN Audio", value: "integrated-2din-audio" },
        { label: "Wireless phone charging", value: "wireless-phone-charging" },
        { label: "Wi-Fi connectivity", value: "wi-fi-connectivity" },
    ],

    "adas-feature": [
        { label: "Forward collision warning", value: "forward-collision-warning" },
        {
            label: "Automatic emergency braking",
            value: "automatic-emergency-braking",
        },
        { label: "Traffic sign recognition", value: "traffic-sign-recognition" },
        { label: "Lane departure warning", value: "lane-departure-warning" },
        { label: "Lane keep assist", value: "lane-keep-assist" },
        { label: "Adaptive cruise control", value: "adaptive-cruise-control" },
        { label: "Adaptive high beam assist", value: "adaptive-high-beam-assist" },
        { label: "Rear cross traffic alert", value: "rear-cross-traffic-alert" },
        { label: "Blind spot monitor", value: "blind-spot-monitor" },
    ],

    "advance-internet-feature": [
        { label: "Over speeding alert", value: "over-speeding-alert" },
        { label: "Over the air (OTA) updates", value: "ota-updates" },
        { label: "Google/Alexa connectivity", value: "google-alexa-connectivity" },
        { label: "SOS/Emergency assistance", value: "sos-emergency-assistance" },
        { label: "SOS button", value: "sos-button" },
        { label: "E-Call & I-Call", value: "e-call-i-call" },
        { label: "Smartwatch App", value: "smartwatch-app" },
        { label: "Live location", value: "live-location" },
        { label: "Remote immobiliser", value: "remote-immobiliser" },
        {
            label: "Unauthorized vehicle entry",
            value: "unauthorized-vehicle-entry",
        },
        { label: "Engine start alarm", value: "engine-start-alarm" },
        {
            label: "Remote vehicle status check",
            value: "remote-vehicle-status-check",
        },
        { label: "PUC expiry", value: "puc-expiry" },
        { label: "Insurance expiry", value: "insurance-expiry" },
        { label: "E-manual", value: "e-manual" },
        { label: "Inbuilt assistant", value: "inbuilt-assistant" },
        { label: "Navigation with live traffic", value: "navigation-live-traffic" },
        { label: "Send POI to vehicle from app", value: "send-poi-to-vehicle" },
        { label: "Live weather", value: "live-weather" },
        { label: "Save Route/Place", value: "save-route-place" },
        { label: "RSA", value: "rsa" },
        { label: "Tow away alert", value: "tow-away-alert" },
        { label: "Valet mode", value: "valet-mode" },
        { label: "Remote AC On/Off", value: "remote-ac-on-off" },
        { label: "Remote Door Lock/Unlock", value: "remote-door-lock-unlock" },
        {
            label: "Remote vehicle ignition Start/Stop",
            value: "remote-ignition-start-stop",
        },
        { label: "Geo-fence alert", value: "geo-fence-alert" },
    ],
};

export const specificationsFields = {
    "engine-and-transmission": [
        { label: "Engine type", value: "engine-type", placeHolder: 'Eg. Petrol, Diesel, Electric' },
        { label: "Max power", value: "max-power", placeHolder: 'Eg. 150 bhp' },
        { label: "Max torque", value: "max-torque", placeHolder: 'Eg. 200 Nm' },
        { label: "No of cylinders", value: "no-of-cylinders", placeHolder: 'Eg. 4' },
        { label: "Valves per cylinder", value: "valves-per-cylinder", placeHolder: 'Eg. 4' },
        { label: "Valve configuration", value: "valve-configuration", placeHolder: '' },
        { label: "Fuel supply system", value: "fuel-supply-system", placeHolder: 'Eg. CRDi' },
        { label: "Turbo charger", value: "turbo-charger", placeHolder: 'Eg. Yes' },
        { label: "Super charge", value: "super-charge", placeHolder: 'Eg. Yes' },
        { label: "Gearbox", value: "gearbox", placeHolder: 'Eg. 5-Speed' },
        { label: "Drive type", value: "drive-type", placeHolder: 'Eg. 4WD' },
        { label: "Battery capacity", value: "battery-capacity", placeHolder: 'Eg. 84kWh' },
        { label: "Motor power", value: "motor-power", placeHolder: 'Eg. 239 kW' },
        { label: "Motor type", value: "motor-type", placeHolder: 'Eg. Permanent Magnet Synchronous Motor' },
        { label: "Range", value: "range", placeHolder: 'Eg. 230 KM' },
        { label: "Battery type", value: "battery-type", placeHolder: "Eg. Lithium-ion" },
        { label: "Battery warranty", value: "battery-warranty", placeHolder: "Eg. 8 Years / 160,000 km" },
        { label: "Charging time (AC)", value: "charging-time-ac", placeHolder: "Eg. 6 hrs" },
        { label: "Charging time (DC)", value: "charging-time-dc", placeHolder: "Eg. 1 hr (0-80%)" },
        { label: "Regenerative braking", value: "regenerative-braking", placeHolder: "Eg. Yes/No" },
        { label: "Regenerative braking levels", value: "regenerative-braking-levels", placeHolder: "Eg. 3 Levels" },
        { label: "Charging port", value: "charging-port", placeHolder: "Eg. CCS2" },
        { label: "Charging options", value: "charging-options", placeHolder: "Eg. AC / DC Fast charging" },
    ],
    "fuel-and-performance": [
        { label: "Mileage ARAI", value: "mileage-arai", placeHolder: "Eg. 16.5 kmpl" },
        { label: "Fuel tank capacity", value: "fuel-tank-capacity", placeHolder: "Eg. 50 L" },
        { label: "Emission norm compliance", value: "emission-norm-compliance", placeHolder: "Eg. BS6" },
        { label: "Top speed", value: "top-speed", placeHolder: "Eg. 180 km/h" },
    ],
    charging: [
        { label: "Charging time (15A Plug point)", value: "charging-time-15a-plug-point", placeHolder: "Eg. 8 hrs" },
        { label: "Charging time (7.2kW AC Fast charger)", value: "charging-time-7.2kw-ac-fast-charger", placeHolder: "Eg. 2 hrs" },
        { label: "Charging time", value: "charging-time", placeHolder: "Eg. 6 hrs" },
        { label: "Fast charging", value: "fast-charging", placeHolder: "Eg. Yes/No" },
    ],
    "suspension-steering-brakes": [
        { label: "Front suspension", value: "front-suspension", placeHolder: "Eg. McPherson strut" },
        { label: "Rear suspension", value: "rear-suspension", placeHolder: "Eg. Torsion beam" },
        { label: "Shock absorbers type", value: "shock-absorbers-type", placeHolder: "Eg. Telescopic" },
        { label: "Steering type", value: "steering-type", placeHolder: "Eg. Power steering" },
        { label: "Turning radius", value: "turning-radius", placeHolder: "Eg. 5.2 m" },
        { label: "Steering column", value: "steering-column", placeHolder: "Eg. Tilt & telescopic" },
        { label: "Steering gear type", value: "steering-gear-type", placeHolder: "Eg. Rack & pinion" },
        { label: "Front brake type", value: "front-brake-type", placeHolder: "Eg. Disc" },
        { label: "Rear brake type", value: "rear-brake-type", placeHolder: "Eg. Drum" },
        { label: "Alloy wheel size Front", value: "alloy-wheel-size-front", placeHolder: "Eg. 17 inch" },
        { label: "Alloy wheel size Rear", value: "alloy-wheel-size-rear", placeHolder: "Eg. 17 inch" },
        { label: "Acceleration (0-100kmph secs)", value: "acceleration-0-100kmph-secs", placeHolder: "Eg. 9.5 s" },
    ],
    "dimensions-and-capacity": [
        { label: "Length", value: "length", placeHolder: "Eg. 4300 mm" },
        { label: "Width", value: "width", placeHolder: "Eg. 1790 mm" },
        { label: "Height", value: "height", placeHolder: "Eg. 1630 mm" },
        { label: "Bootspace", value: "bootspace", placeHolder: "Eg. 450 L" },
        { label: "Seating capacity", value: "seating-capacity", placeHolder: "Eg. 5" },
        { label: "Ground clearance", value: "ground-clearance", placeHolder: "Eg. 190 mm" },
        { label: "Wheel base", value: "wheel-base", placeHolder: "Eg. 2600 mm" },
        { label: "No of doors", value: "no-of-doors", placeHolder: "Eg. 5" },
        { label: "Front tread", value: "front-tread", placeHolder: "Eg. 1530 mm" },
        { label: "Rear tread", value: "rear-tread", placeHolder: "Eg. 1540 mm" },
        { label: "Kerb weight", value: "kerb-weight", placeHolder: "Eg. 1350 kg" },
        { label: "Gross weight", value: "gross-weight", placeHolder: "Eg. 1900 kg" },
    ],
    "other-details": [
        { label: "Accidental", value: "accidental", placeHolder: "Eg. Yes/No" },
        { label: "Battery condition", value: "battery-condition", placeHolder: "Eg. Good/Average/Weak" },
        { label: "Tyre condition", value: "tyre-condition", placeHolder: "Eg. New/Used/Worn" },
        { label: "Vehicle certified", value: "vehicle-certified", placeHolder: "Eg. Yes/No" },
        { label: "Spare wheel and box", value: "spare-wheel-and-box", placeHolder: "Eg. Yes/No" },
        { label: "Global NCAP rating", value: "global-ncap-rating", placeHolder: "Eg. 4 Star" },
        { label: "No of airbags", value: "no-of-airbags", placeHolder: "Eg. 6" },
    ],

};